### ISSUE TITLE
Use at least the ad_storage, and analytics_storage consent types on the setDefaultConsent Call

### ISSUE THREAD

**Issue by semisight** [Measurelab/measurelab_civic_cookie_banner_tag_template#1]
https://github.com/Measurelab/measurelab_civic_cookie_banner_tag_template/blob/fcd40dfee36c5fad57abbde988c043787944311b/template.tpl#L718

When reviewing your template we've noticed that the [setDefaultConsentState](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) call does not include defaults for `ad_storage` and `analytics_storage`. A minimum default is required for each of these settings by GTM policy.

**Comment by victorsarker** [comment]
Hi @semisight I've just committed to master an overhauled version of the tag template which should address this issue. `ad_storage` and `analytics_storage` (along with `ad_user_data` and `ad_personalization` are now set with dropdowns and must have a default value.
